### ISSUE TITLE
Add Fields drop down is empty

### ISSUE THREAD

**Issue by cdlenfert** [dougblackjr/ee-json-ld#1]
Hi, I've recently installed this addon on our site running EE 4.3.1. When I try to add a field the drop down for Add Fields is empty. Is there something I'm missing, or is the addon possibly broken on the current version of EE 4?

**Comment by dougblackjr** [comment]
@cdlenfert What type did you choose? Are you getting any Javascript errors?

**Comment by cdlenfert** [comment]
@dougblackjr Thanks for the quick reply. The type I'm choosing is "event". Here's what I'm seeing in the console.
`jquery.js?v=1529332137:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.js?v=1529332137:4
jquery.js?v=1529332137:4 Failed to load resource: the server responded with a status of 404 (Not Found)
send @ jquery.js?v=1529332137:4
load_edit_form.js:37 Object
load_edit_form.js:45 Uncaught TypeError: Cannot read property 'template_text' of undefined
    at HTMLDocument.<anonymous> (load_edit_form.js:45)
    at l (jquery.js?v=1529332137:3)
    at Object.fireWith [as resolveWith] (jquery.js?v=1529332137:3)
    at Function.ready (jquery.js?v=1529332137:3)
    at HTMLDocument.s (jquery.js?v=1529332137:2)
2/admin/admin.php?/cp/addons/settings/json_ld/ajaxcall:1 Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:193 Object
app.js:50 Object
/admin/admin.php?/cp/addons/settings/json_ld/ajaxcall:1 Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:193 Objectabort: ƒ (e)always: ƒ ()complete: ƒ ()done: ƒ ()error: ƒ ()fail: ƒ ()getAllResponseHeaders: ƒ ()getResponseHeader: ƒ (e)overrideMimeType: ƒ (e)pipe: ƒ ()progress: ƒ ()promise: ƒ (e)readyState: 4responseText: "<html>
↵<head><title>404 Not Found</title></head>
↵<body bgcolor="white">
↵<center><h1>404 Not Found</h1></center>
↵<hr><center>nginx/1.10.3 (Ubuntu)</center>
↵</body>
↵</html>
↵
↵
↵
↵
↵
↵
↵"setRequestHeader: ƒ (e,t)state: ƒ ()status: 404statusCode: ƒ (e)statusText: "Not Found"success: ƒ ()then: ƒ ()__proto__: Object
/admin/admin.php?/cp/addons/settings/json_ld/ajaxcall:1 Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:193 Object
/admin/admin.php?/cp/addons/settings/json_ld/ajaxcall:1 Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:193 Object
/admin/admin.php?/cp/addons/settings/json_ld/ajaxcall:1 Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:193 Object
/admin/admin.php?/cp/addons/settings/json_ld/ajaxcall:1 Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:193 Object
/admin/admin.php?/cp/addons/settings/json_ld/ajaxcall:1 Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:193 Object
/admin/admin.php?/cp/addons/settings/json_ld/ajaxcall:1 Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:193 Object
/admin/admin.php?/cp/addons/settings/json_ld/ajaxcall:1 Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:193 Object
/admin/admin.php?/cp/addons/settings/json_ld/ajaxcall:1 Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:193 Object
/admin/admin.php?/cp/addons/settings/json_ld/ajaxcall:1 Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:193 Object
/admin/admin.php?/cp/addons/settings/json_ld/ajaxcall:1 Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:193 Object
/admin/admin.php?/cp/addons/settings/json_ld/ajaxcall:1 Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:193 Object
/admin/admin.php?/cp/addons/settings/json_ld/ajaxcall:1 Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:193 Object
/admin/admin.php?/cp/addons/settings/json_ld/ajaxcall:1 Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:193 Object
/admin/admin.php?/cp/addons/settings/json_ld/ajaxcall:1 Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:193 Object
/admin/admin.php?/cp/addons/settings/json_ld/ajaxcall:1 Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:193 Object
/admin/admin.php?/cp/addons/settings/json_ld/ajaxcall:1 Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:193 Object`

**Comment by dougblackjr** [comment]
@cdlenfert Do you have the theme files installed correctly? This may be because of a missing JS file.

Edit: Sorry for the accidental close.

**Comment by cdlenfert** [comment]
According to our developer everything is uploaded properly. The addon installs without error. It's only when I get to the Add Fields step that I'm having the issue. Tried re-uploading the addon files. Can you confirm it should work with EE 4.3.1?

**Comment by dougblackjr** [comment]
It definitely works with 4.3.1, I just tested it. Can you screenshot your console when you are having the error, as well as your folder structure in your Themes folder?

**Comment by cdlenfert** [comment]
Thanks for confirming. Here are the screenshots.

![kaufman-json-ld-addon](https://user-images.githubusercontent.com/17277745/41943567-1fec37b6-7961-11e8-8811-16cba8b9f007.jpg)
![theme-files](https://user-images.githubusercontent.com/17277745/41943568-1ffc57f4-7961-11e8-95f2-5372665f4937.png)
![user-addon-files](https://user-images.githubusercontent.com/17277745/41943569-20112c10-7961-11e8-9030-298794b23e89.png)

**Comment by dougblackjr** [comment]
I'm unable to reproduce. You had mentioned that there was an error in your console; can you send a screenshot of that error? I know you had sent it above, but seeing it in context would be really helpful.

**Comment by cdlenfert** [comment]
Thanks for checking. I meant to upload this.
![ee-json-addon-console-errors](https://user-images.githubusercontent.com/17277745/41980903-e2fa0a0c-79e4-11e8-9467-397319041084.png)

**Comment by dougblackjr** [comment]
Ah, I think I see the issue. It looks like you access your admin panel by going to `/admin`, yes? I think I have it hardcoded in the addon, which I can address, if this is the case.

**Comment by cdlenfert** [comment]
Thanks Doug. Yes I'm accessing the admin panel at `/admin` as you mentioned.  I appreciate your willingness to address my issue. Is there a workaround in the meantime?

**Comment by dougblackjr** [comment]
For now, you can change any js in the reopo that points to `admin.php?/cp/addons/settings/json_ld` to your path `admin/admin.php?/cp/addons/settings/json_ld`. I'll work on a release for this weekend to fix that.

**Comment by dougblackjr** [comment]
@cdlenfert Fixed this in [version 1.1](https://github.com/dougblackjr/ee-json-ld/releases/tag/1.1)! Thank you for pointing out this issue!

**Comment by cdlenfert** [comment]
I hit another wall after installing the updated addon.

`Fatal error: Uncaught Error: Class 'Spatie\\SchemaOrg\\event' not found in /var/www/kaufman-music-center/www.kaufmanmusiccenter.org_system/user/addons/json_ld/mcp.json_ld.php:303\nStack trace:\n#0 [internal function]: Json_ld_mcp->ajaxcall()\n#1 /var/www/kaufman-music-center/www.kaufmanmusiccenter.org_system/ee/EllisLab/ExpressionEngine/Controller/Addons/Addons.php(1661): call_user_func_array(Array, Array)\n#2 /var/www/kaufman-music-center/www.kaufmanmusiccenter.org_system/ee/EllisLab/ExpressionEngine/Controller/Addons/Addons.php(945): EllisLab\\ExpressionEngine\\Controller\\Addons\\Addons->getModuleSettings('json_ld', 'ajaxcall', Array)\n#3 [internal function]: EllisLab\\ExpressionEngine\\Controller\\Addons\\Addons->settings('json_ld', 'ajaxcall')\n#4 /var/www/kaufman-music-center/www.kaufmanmusiccenter.org_system/ee/EllisLab/ExpressionEngine/Core/Core.php(240): call_user_func_array(Array, Array)\n#5 /var/www/kaufman-music-center/www.kaufmanmusiccenter.org_system/ee/EllisLab/ExpressionEngine/Core/Core.php(109): EllisLab\\ExpressionEngine\\ in /var/www/kaufman-music-center/www.kaufmanmusiccenter.org_system/user/addons/json_ld/mcp.json_ld.php on line 303`

**Comment by dougblackjr** [comment]
That's odd. Do me a favor and create a new issue for this; I'll get to work right away
