### ISSUE TITLE
Fatal error after focus in 

### ISSUE THREAD

**Issue by cdlenfert** [dougblackjr/ee-json-ld#2]
I've installed and gone to the admin page to create a new template. When I choose a type of "event" the following error results.

![image](https://user-images.githubusercontent.com/17277745/42230036-366d5a9e-7ea5-11e8-8217-aa0665f83817.png)

**full error text:**
`"<br />\n<b>Fatal error</b>:  Uncaught Error: Class 'Spatie\\SchemaOrg\\event' not found in /var/www/kaufman-music-center/www.kaufmanmusiccenter.org_system/user/addons/json_ld/mcp.json_ld.php:303\nStack trace:\n#0 [internal function]: Json_ld_mcp-&gt;ajaxcall()\n#1 /var/www/kaufman-music-center/www.kaufmanmusiccenter.org_system/ee/EllisLab/ExpressionEngine/Controller/Addons/Addons.php(1661): call_user_func_array(Array, Array)\n#2 /var/www/kaufman-music-center/www.kaufmanmusiccenter.org_system/ee/EllisLab/ExpressionEngine/Controller/Addons/Addons.php(945): EllisLab\\ExpressionEngine\\Controller\\Addons\\Addons-&gt;getModuleSettings('json_ld', 'ajaxcall', Array)\n#3 [internal function]: EllisLab\\ExpressionEngine\\Controller\\Addons\\Addons-&gt;settings('json_ld', 'ajaxcall')\n#4 /var/www/kaufman-music-center/www.kaufmanmusiccenter.org_system/ee/EllisLab/ExpressionEngine/Core/Core.php(240): call_user_func_array(Array, Array)\n#5 /var/www/kaufman-music-center/www.kaufmanmusiccenter.org_system/ee/EllisLab/ExpressionEngine/Core/Core.php(109): EllisLab\\ExpressionEngine\\ in <b>/var/www/kaufman-music-center/www.kaufmanmusiccenter.org_system/user/addons/json_ld/mcp.json_ld.php</b> on line <b>303</b><br />\n"
`
I've also noticed the version number was not updated to 1.1.0.
![image](https://user-images.githubusercontent.com/17277745/42230652-bca4d7b2-7ea6-11e8-95dd-91103162e485.png)

**Comment by dougblackjr** [comment]
Thank you! I'll work on this.

**Comment by cdlenfert** [comment]
Thanks Doug. Just checking to see if you've been able to make any progress on a fix. No worries if not, I'll just need to go another direction for adding structured data markup on my project.

**Comment by dougblackjr** [comment]
I am working on this. Should have something by the end of the weekend.

**Comment by dougblackjr** [comment]
Fixed this on latest release: https://github.com/dougblackjr/ee-json-ld/releases/tag/v1.2
