### ISSUE TITLE
EE5 and lists of entries

### ISSUE THREAD

**Issue by next-direction** [dougblackjr/ee-json-ld#3]
Hi, 
I currently setup a blog and like to add some json-ld to it.

Before I try your addon, I have two questions:
- Is this addon compatible with EE5?
- Is it possible to create a list of entries, e.g. Blog entity with several BlogPosts?

Thanks

**Comment by dougblackjr** [comment]
Yes, it will work with EE4 (just haven't versioned it up).

It's not currently possible to do the list of entries in the plugin. But, the reality is that this plugin is a little overkill. If you use it you may just want to use it to create your initial template with all of the fields, and then copy and paste the code into your own template partial. It's on my list to do this, but I have not had time to do so.

Let me know how I can help.
